### ISSUE TITLE
Translate the Windows batch files to Linux

### ISSUE THREAD

**Issue by andrerpena** [radiscope/radiscope-web#13]
@JonatanSalas , this folder contains 3 batch files for database manipulation: https://github.com/radiscope/radiscope-web/tree/master/db

Can you please create the corresponding LINUX versions? 

Thank you.

**Comment by JonatanSalas** [comment]
I will take it so! You are welcome!

**Comment by danigomez** [comment]
Hey @andrerpena ! We were thinking to convert the batch files to js files and add it in the package.json in order to only mantain a single file to install the DB, looking at the .bat the only difference in Linux will be in the "set" command, so using Node process.exec we can do the script multi-platform.

**Comment by andrerpena** [comment]
I support the idea =). Thanks

Em 19 de set de 2016 10:06, "Daniel Gómez" notifications@github.com
escreveu:

**Comment by danigomez** [comment]
Take a look at this!! It's done!

**Comment by andrerpena** [comment]
I'll look at it first thing when I get home! Thank you! Looks promising!

**Comment by andrerpena** [comment]
Perfect! Thank you!
